Repository ebizbase/dev-infras, pull requests merged in 2024-11, with the labels that each got.

#2 feat(devcontainer): add base devcontainer and node devcontainer
  images/devcontainer/Dockerfile
  images/devcontainer/README.md
  images/devcontainer/project.json
  release-config.json
  release-manifest.json
Labels: size/m, pairing-wanted

#3 chore(release): release v1.0.0
  images/devcontainer/CHANGELOG.md
  release-manifest.json
Labels: autorelease: pending

#16 chore: patch
  .github/workflows/daily-chores.yaml
  .github/workflows/release.yaml
  .github/workflows/test.yaml
  .trunk/configs/.gitleaks.toml
  .trunk/configs/.markdownlint.yaml
  .trunk/configs/.yamllint.yaml
  README.md
  devcontainer-images/playwright-devcontainer/.devcontainer/Dockerfile
  devcontainer-images/playwright-devcontainer/.devcontainer/devcontainer.json
  devcontainer-images/playwright-devcontainer/project.json
Labels: size/s

#13 chore(release): release v0.0.1
  devcontainer-images/playwright-devcontainer/CHANGELOG.md
  release-manifest.json
Labels: autorelease: pending
